"""add_edgerouter_and_neighbor_models

Revision ID: b9754885caeb
Revises: 1a31ce608336
Create Date: 2025-10-02 16:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b9754885caeb'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edgerouter',
    sa.Column('router_ip', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=False),
    sa.Column('device_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('mac_address', sqlmodel.sql.sqltypes.AutoString(length=17), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('serial_number', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('board_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('uptime', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('cpu', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('serial_number')
    )
    op.create_index(op.f('ix_edgerouter_router_ip'), 'edgerouter', ['router_ip'], unique=False)
    op.create_table('neighbordevice',
    sa.Column('router_ip', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('device_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('mac_address', sqlmodel.sql.sqltypes.AutoString(length=17), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('interface', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('edge_router_serial', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('discovered_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['edge_router_serial'], ['edgerouter.serial_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_neighbordevice_mac_address'), 'neighbordevice', ['mac_address'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_neighbordevice_mac_address'), table_name='neighbordevice')
    op.drop_table('neighbordevice')
    op.drop_index(op.f('ix_edgerouter_router_ip'), table_name='edgerouter')
    op.drop_table('edgerouter')
    # ### end Alembic commands ###
